[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:matplotlib
    ignore::PendingDeprecationWarning:matplotlib
    ignore::pyparsing.PyparsingDeprecationWarning
