import struct
import numpy as np
import exifread
from pathlib import Path

from .config import (
    PROFILE_TONE_CURVE,
    SENSOR_WIDTH, SENSOR_HEIGHT, SENSOR_RAW_STRIP_BYTES,
)

# TIFF / DNG tag type codes (TIFF 6.0 spec § Image File Directory).
_BYTE, _ASCII, _SHORT, _LONG, _RATIONAL, _SRATIONAL, _FLOAT = 1, 2, 3, 4, 5, 10, 11

def _pack_rational_array(vals: list) -> bytes:
    b = bytearray()
    denom = 10000
    for v in vals:
        num = int(round(max(0.0, float(v)) * denom))
        b += struct.pack('<II', num, denom)
    return b

def _pack_srational_array(vals: list) -> bytes:
    b = bytearray()
    denom = 10000
    for v in vals:
        num = int(round(float(v) * denom))
        b += struct.pack('<ii', num, denom)
    return b

def _pack_float_array(vals) -> bytes:
    return struct.pack(f'<{len(vals)}f', *vals)

def _pack_ifd(tags: list, current_offset: int, next_ifd_offset: int = 0) -> bytes:
    tags = sorted(tags, key=lambda x: x[0])
    entries, extra = bytearray(), bytearray()
    entries += struct.pack('<H', len(tags))
    extra_offset = current_offset + 2 + len(tags) * 12 + 4
    
    for tag_id, type_val, count, val_bytes in tags:
        if len(val_bytes) <= 4:
            padded = val_bytes + b'\x00' * (4 - len(val_bytes))
            entries += struct.pack('<HHI4s', tag_id, type_val, count, padded)
        else:
            entries += struct.pack('<HHII', tag_id, type_val, count, extra_offset + len(extra))
            extra += val_bytes
            if len(extra) % 2 == 1: extra += b'\x00'
                
    entries += struct.pack('<I', next_ifd_offset)
    return entries + extra

def export_dng(source_path: str, output_path: str, thumbnail_rgb: np.ndarray, profile_name: str = 'Flashback Standard') -> bool:
    try:
        # Pass the source DNG's 10-bit raw strip through verbatim.
        with open(source_path, 'rb') as f:
            tags = exifread.process_file(f, details=False)
            
        raw_off = int(tags['Image StripOffsets'].values[0]) if 'Image StripOffsets' in tags else 2048
        raw_len = int(tags['Image StripByteCounts'].values[0]) if 'Image StripByteCounts' in tags else SENSOR_RAW_STRIP_BYTES
        
        with open(source_path, 'rb') as f:
            f.seek(raw_off)
            raw_bytes = f.read(raw_len)

        # AsShotNeutral — measured from a D50 grey patch, no analog-balance
        # scaling. Must match core.processor.ASN_D50.
        asn = [0.541, 1.0, 0.597]

        # ForwardMatrix1 / ColorMatrix1 — calibrated under D50 daylight.
        # Generated by tools/generate_matrices_from_colorchart.py (--illuminant d50).
        fm1 = [0.53086, 0.22116, 0.21219, 0.08570, 0.98930, -0.07500, 0.04526, -0.37228,
 1.15192]
        cm1 = [1.13201, -0.44377, -0.13778, -0.13053, 1.02710, 0.10343, -0.08365,
 0.28262, 0.43783]

        # ForwardMatrix2 / ColorMatrix2 — calibrated under Standard Illuminant A (~2856K)
        # Shoot ColorChecker under Bellight 75W, run: python tools/generate_matrices_from_colorchart.py --illuminant tungsten
        # then paste the output values here.
        fm2 = [0.26113, 0.47499, 0.22809, -0.17676, 1.14599, 0.03076, -0.08359, -0.92293,
 1.83141]
        cm2 = [2.15297, -1.02221, -0.21252, 0.36968, 0.66294, -0.03261, 0.10417, 0.11105,
 0.16592]

        # Thumbnail: fall back to a black placeholder if nothing usable was passed.
        if thumbnail_rgb is None or thumbnail_rgb.size == 0:
            thumbnail_rgb = np.zeros((120, 160, 3), dtype=np.uint8)
        elif thumbnail_rgb.dtype != np.uint8:
            thumbnail_rgb = (np.clip(thumbnail_rgb, 0.0, 1.0) * 255).astype(np.uint8)
        thumb_h, thumb_w = thumbnail_rgb.shape[:2]
        thumb_bytes = thumbnail_rgb.tobytes()

        def build_tags(subifd_off: int, thumb_off: int, raw_off: int):
            make_str = b'Flashback\x00'
            model_str = b'Flashback ONE35\x00'
            unique_model_str = b'Flashback ONE35 V2\x00'
            profile_name_str = profile_name.encode() + b'\x00'
            tone_curve_bytes = _pack_float_array(PROFILE_TONE_CURVE)

            ifd0 = [
                (254, _LONG, 1, struct.pack('<I', 1)),                                    
                (256, _LONG, 1, struct.pack('<I', thumb_w)),                              
                (257, _LONG, 1, struct.pack('<I', thumb_h)),                              
                (258, _SHORT, 3, struct.pack('<HHH', 8, 8, 8)),                           
                (259, _SHORT, 1, struct.pack('<H', 1)),                                   
                (262, _SHORT, 1, struct.pack('<H', 2)),                                   
                (271, _ASCII, len(make_str), make_str),                                      
                (272, _ASCII, len(model_str), model_str),                                
                (273, _LONG, 1, struct.pack('<I', thumb_off)),
                (274, _SHORT, 1, struct.pack('<H', 1)),                                   
                (277, _SHORT, 1, struct.pack('<H', 3)),                                   
                (278, _LONG, 1, struct.pack('<I', thumb_h)),                              
                (279, _LONG, 1, struct.pack('<I', len(thumb_bytes))),                     
                (282, _RATIONAL, 1, _pack_rational_array([300.0])),                       
                (283, _RATIONAL, 1, _pack_rational_array([300.0])),                       
                (284, _SHORT, 1, struct.pack('<H', 1)),                                   
                (296, _SHORT, 1, struct.pack('<H', 2)),                                   
                (330, _LONG, 1, struct.pack('<I', subifd_off)),  
                 
                # --- DNG VERSION ---
                (50706, _BYTE, 4, b'\x01\x04\x00\x00'),       # DNGVersion 1.4.0.0
                (50707, _BYTE, 4, b'\x01\x02\x00\x00'),       # DNGBackwardVersion 1.2.0.0
                
                (50708, _ASCII, len(unique_model_str), unique_model_str),
                
                # --- COLOR MATRICES ---
                (50721, _SRATIONAL, 9, _pack_srational_array(cm1)),
                (50722, _SRATIONAL, 9, _pack_srational_array(cm2)),
                (50964, _SRATIONAL, 9, _pack_srational_array(fm1)),
                (50965, _SRATIONAL, 9, _pack_srational_array(fm2)),
                (50731, _RATIONAL, 3, _pack_rational_array(asn)),            
                (50778, _SHORT, 1, struct.pack('<H', 23)),   # CalibrationIlluminant1: D50
                (50779, _SHORT, 1, struct.pack('<H', 17)),   # CalibrationIlluminant2: Standard Light A

                # --- EMBEDDED PROFILE ---
                (50936, _ASCII, len(profile_name_str), profile_name_str),
                (50940, _FLOAT, len(PROFILE_TONE_CURVE), tone_curve_bytes),
                (50941, _LONG, 1, struct.pack('<I', 0)),     # ProfileEmbedPolicy: allow copying
            ]
            
            subifd = [
                (254, _LONG, 1, struct.pack('<I', 0)),                                    
                (256, _LONG, 1, struct.pack('<I', SENSOR_WIDTH)),
                (257, _LONG, 1, struct.pack('<I', SENSOR_HEIGHT)),
                (258, _SHORT, 1, struct.pack('<H', 10)),
                (259, _SHORT, 1, struct.pack('<H', 1)),
                (262, _SHORT, 1, struct.pack('<H', 32803)),
                (273, _LONG, 1, struct.pack('<I', raw_off)),
                (277, _SHORT, 1, struct.pack('<H', 1)),
                (278, _LONG, 1, struct.pack('<I', SENSOR_HEIGHT)),
                (279, _LONG, 1, struct.pack('<I', len(raw_bytes))),
                (282, _RATIONAL, 1, _pack_rational_array([300.0])),                       
                (283, _RATIONAL, 1, _pack_rational_array([300.0])),                       
                (284, _SHORT, 1, struct.pack('<H', 1)),                                   
                (296, _SHORT, 1, struct.pack('<H', 2)),                                   
                (33421, _SHORT, 2, struct.pack('<HH', 2, 2)),                             
                (33422, _BYTE, 4, b'\x00\x01\x01\x02'),                                   
                (50710, _BYTE, 3, b'\x00\x01\x02'),                                      
                (50711, _SHORT, 1, struct.pack('<H', 1)),                                 
                (50713, _SHORT, 2, struct.pack('<HH', 2, 2)),                             
                (50714, _SHORT, 4, struct.pack('<HHHH', 64, 64, 64, 64)),                 
                (50717, _LONG, 1, struct.pack('<I', 1023)),                               
                (50718, _RATIONAL, 2, _pack_rational_array([1.0, 1.0])),                  
                (50719, _LONG, 2, struct.pack('<II', 0, 0)),                              
                (50720, _LONG, 2, struct.pack('<II', SENSOR_WIDTH, SENSOR_HEIGHT)),
                (50829, _LONG, 4, struct.pack('<IIII', 0, 0, SENSOR_HEIGHT, SENSOR_WIDTH)),
            ]
            return ifd0, subifd

        dummy_ifd0, dummy_subifd = build_tags(0, 0, 0)
        len_ifd0 = len(_pack_ifd(dummy_ifd0, 8))
        actual_subifd_off = 8 + len_ifd0
        len_subifd = len(_pack_ifd(dummy_subifd, actual_subifd_off))
        actual_thumb_off = actual_subifd_off + len_subifd
        actual_raw_off = actual_thumb_off + len(thumb_bytes)
        
        final_ifd0, final_subifd = build_tags(actual_subifd_off, actual_thumb_off, actual_raw_off)
        
        with open(output_path, 'wb') as f:
            f.write(b'II\x2a\x00\x08\x00\x00\x00')
            f.write(_pack_ifd(final_ifd0, 8))
            f.write(_pack_ifd(final_subifd, actual_subifd_off))
            f.write(thumb_bytes)
            f.write(raw_bytes)
            
        print(f"✓ DNG Exported: {output_path}")
        return True
    except Exception as exc:
        print(f"✗ DNG export failed: {exc}")
        return False
